@BASE=http://localhost:3000


###
GET {{BASE}}

###
GET {{BASE}}/healthcheck

###
GET {{BASE}}/hello/12?name=jaspreet
content-type: application/json

###
POST {{BASE}}/hello
content-type: application/json

{
  "name": "Jaspreet",
  "age": 120
}